fingerprint_types = ['onscreen', 'rear', 'powerbutton']
display_types = ['normal', 'curved', 'flip']
#  charger_types = ['wireless', 'wired']
headphone_jack = ['available', 'none']
size = ['normal', 'large']

FEATURE_TYPES = {
    "display": display_types,
    "fingerprint": fingerprint_types,
    "headphone-jack": headphone_jack,
    "size": size,
}
FEATURE_CATEGORY = ["camera", "display", "battery",
                    "face recognition", "fingerprint", "speakers", "headphone-jack", "headphone", "wireless-charger", "charger", "size"]

category_synonyms = [["camera"],
                     ["display", "screen"],
                     ["battery"],
                     ["face recognition", "face id",
                      "recognition", "face-recognition"],
                     ["fingerprint", "reader"],
                     ["speakers", "speaker", "sound"],
                     ["headphone jack", "headphone-jack"],
                     ["headphone", "earphone"],
                     ["charger", "charge", "charging"],
                     ["wireless charger", "wireless-charge",
                         "wireless charging", "wireless-charging"],
                     ["size"]
                     ]
phones = {
    fingerprint_types[0]: [
        'oneplus-6t',
        'oneplus-7t',
        'oneplus-7-pro',
        'oneplus-8-pro',
        'oneplus-8t',
        'samsung-galaxy-a50',
        'samsung-galaxy-note-10-lite',
        'samsung-electronics-galaxy-note-20',
        'samsung-galaxy-a31',
        'samsung-galaxy-a51',
        'samsung-galaxy-a71',
        'huawei-p30pro'
    ],
    fingerprint_types[1]: [
        'oneplus-6',
        'oneplus-nord-n100',
        'oneplus-6t',
        'samsung-galaxy-a21s',
        'samsung-galaxy-a70',
        'google-pixel-4a',
        'huawei-p30-lite'
    ],
    fingerprint_types[2]: [
        'realme-6',
        'realme-6-pro',
        'samsung-galaxy-j3-prime'
    ],
    display_types[0]: [
        'samsung-galaxy-note-8',
        "samsung-galaxy-s9",
        'apple-iphone-11',
        'samsung-galaxy-a21s',
        'apple-iphone-7-plus',
        'apple-iphone-7',
        "samsung-galaxy-s10",
        'apple-iphone-8-plus',
        'samsung-galaxy-a10s',
        'apple-iphone-8',
        #  'samsung-galaxy-a01',
        #  'apple-iphone-se',
        #  'samsung-galaxy-a01-core',
        #  'apple-iphone-x',
        #  'samsung-galaxy-note-10-lite',
        #  'apple-iphone-xr',
        #  'apple-iphone-xs-max',
        #  'apple-iphone-xs',
        #  'samsung-galaxy-a10e',
        #  'samsung-galaxy-a11',
    ],
    display_types[1]: [
        "samsung-galaxy-s10+",
        "samsung-galaxy-s9+",
        'huawei-p30-lite',
        'samsung-electronics-galaxy-note-20',
        'huawei-p30pro',
        'samsung-galaxy-a70',
        'samsung-galaxy-a50',
        'oneplus-7-pro',
        'oneplus-8-pro',
        'google-pixel-4',
        'google-pixel-4a',
        #  'samsung-galaxy-a51',
        #  'samsung-galaxy-a71',
    ],
    display_types[2]: [
        'samsung-galaxy-z-flip'
    ],
    headphone_jack[0]: [
        'huawei-honor-9',
        'huawei-honor-8s',
        'samsung-galaxy-a50',
        'samsung-galaxy-note-10-lite',
        'google-pixel-4a',
        'huawei-p30-lite',
        'samsung-galaxy-a01-core',
        'motorola-moto-z-play',
        'samsung-galaxy-a01',
        'samsung-galaxy-a10e',
        #  'samsung-galaxy-a70',
        #  'samsung-galaxy-a71',
        #  'samsung-galaxy-a10s',
        #  'samsung-galaxy-a11',
        #  'samsung-galaxy-a21s',
        #  'samsung-galaxy-a31',
        #  'samsung-galaxy-a51',

    ],
    headphone_jack[1]: [
        'oneplus-7t',
        'oneplus-7-pro',
        'oneplus-8t',
        'oneplus-8-pro',
        'google-pixel-4',
        'huawei-p30pro',
        'samsung-electronics-galaxy-note-20',
        'apple-iphone-11',
        'apple-iphone-7-plus',
        'apple-iphone-7',
        'apple-iphone-8-plus',
        #  'apple-iphone-8',
        #  'apple-iphone-x',
        #  'apple-iphone-xr',
        #  'apple-iphone-xs-max',
        #  'apple-iphone-xs',

    ],
    size[0]: [
        'apple-iphone-8',
        'samsung-galaxy-a50',
        'apple-iphone-11',
        'apple-iphone-7',
        'samsung-galaxy-a01-core',
        'samsung-galaxy-a01',
        'samsung-galaxy-a10e',
        'motorola-moto-z-play',
        'google-pixel-4',
        'google-pixel-4a',
        'samsung-galaxy-a10s',
        'samsung-galaxy-a11',
        #  'apple-iphone-x',
        #  'apple-iphone-xr',
        #  'apple-iphone-xs',
        #  'apple-iphone-se',

    ],
    size[1]: ['samsung-galaxy-note-8',
              'apple-iphone-8-plus',
              'apple-iphone-7-plus',
              'apple-iphone-xs-max',
              'samsung-galaxy-note-10-lite',
              'samsung-electronics-galaxy-note-20',
              'samsung-galaxy-a21s',
              'samsung-galaxy-a31',
              'samsung-galaxy-a51',
              'samsung-galaxy-a70',
              'samsung-galaxy-a71',
              'huawei-p30-lite',
              'huawei-p30pro', ]
}
