version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/sdgp
   runas: ubuntu
 # - source: requirements.txt
   # destination: /home/ubuntu/python-flask-service
permissions:
  - object: /home/ubuntu/sdgp
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file
      - directory
