MODELS = {
    'Galaxy A51': 'Samsung Galaxy A51',
    'Galaxy A70': 'Samsung Galaxy A70',
    'Galaxy A71': 'Samsung Galaxy A70',
    'Galaxy J3 Prime': 'Samsung Galaxy J3 Prime',
    'Galaxy Note 10 Plus': 'Samsung Galaxy Note 10\+',
    'Galaxy Note 10 Lite': 'Samsung Galaxy Note 10 Lite',
    'Galaxy Note 5': 'Samsung Galaxy Note 5',
    'Note 9': 'Galaxy Note 9',
    'Galaxy s10 Plus': 'Samsung Galaxy S10\+',
    'Galaxy S10E': 'Samsung Galaxy S10E',
    'Galaxy S20 Plus': 'Samsung Galaxy S20\+',
    'Galaxy S6': 'Samsung Galaxy S6',
    'Galaxy S7': 'Samsung Galaxy S7',
    'Galaxy S8 Plus': 'Samsung Galaxy S8\+',
    'Galaxy S9 Plus': 'Samsung Galaxy S9\+',
    'Galaxy XCover Pro': 'Samsung Galaxy XCover Pro',
    'Galaxy Z Flip': 'Samsung Galaxy Z Flip',
    'Galaxy A50': 'Samsung Galaxy A50',
    'Galaxy A20S': 'Samsung Galaxy A20S',
    'Galaxy A21S': 'Samsung Galaxy A21S',
    'Galaxy A30S': 'Samsung Galaxy A30S',
    'Galaxy A31': 'Samsung Galaxy A31',
    'Galaxy A11': 'Samsung Galaxy A11',
    'Galaxy A10S': 'Samsung Galaxy A10S',
    'Galaxy A10E': 'Samsung Galaxy A10E',
    'Galaxy A01 Core': 'Samsung Galaxy A01 Core',
    'Galaxy Note 20': 'Samsung Electronics Galaxy Note 20',
    'Galaxy S9': 'Samsung Galaxy S9[^+]+',
    'Galaxy Note 10': 'Samsung Galaxy Note 10[^+]+',
    'Galaxy S10': 'Samsung Galaxy S10[^(+|e)]+',
    'Galaxy S20': 'Samsung Galaxy S20 ',
    'Galaxy A01': 'Samsung Galaxy A01 [^(Core)]+',
    'Galaxy S8': 'Galaxy S8 ',
    'Galaxy Note 8': 'Galaxy Note 8|Galaxy Note8',
    'OnePlus 7 Pro': 'OnePlus 7 Pro',
    'OnePlus 7T': 'OnePlus 7T',
    'OnePlus 6': 'OnePlus 6[^T]+',
    'OnePlus 8 Pro': 'OnePlus 8 Pro',
    'OnePlus 8T': 'OnePlus 8T',
    'Nord N100': 'OnePlus Nord N100',
    'OnePlus 6T': 'OnePlus 6T',
    'Pixel 4 XL': 'Pixel 4 XL',
    'Pixel 3 XL': 'Pixel 3 XL',
    'Pixel 3a': 'Pixel 3a',
    'Pixel 4a': 'Pixel 4a',
    'Pixel 5': 'Pixel 5',
    'Pixel 2 XL': 'Pixel 2 XL',
    'Pixel 4 ': 'Pixel 4 [^XL]+',
    'Pixel 3': 'Pixel 3 [^XL]+',
    'Pixel 2': 'Pixel 2 [^XL]+',
    'Honor 8S': 'Honor 8S',
    'Honor 9X': 'Honor 9X',
    'Huawei P30PRO': 'Huawei P30PRO',
    'Huawei E837': 'Huawei E837',
    'Honor 10 Lite': 'Honor 10 Lite',
    'Huawei Honor 9': 'Huawei Honor 9',
    'Huawei Nova 5T': 'Huawei Nova 5T',
    'Huawei P30 Lite': 'Huawei P30 Lite',
    'Huawei Y5': 'Huawei Y5',
    'Huawei Mate 10 Pro': 'Huawei Mate 10 Pro',
    'Realme 6': 'Realme 6 [^Pro]+',
    'Realme 6 Pro': 'Realme 6 Pro',
    'Xperia 10': 'Sony Xperia 10',
    'Xperia 1': 'Sony Xperia 1',
    'Xperia L1': 'Sony Xperia L1',
    'Xperia XZ2': 'Sony Xperia XZ2',
    'Xperia XZ Premium': 'Sony Xperia XZ Premium',
    'ZenFone Max': 'ASUS ZenFone Max',
    'Desire 530': 'HTC Desire 530',
    'HTC One M7': 'HTC One \(?M7\)?',
    'HTC One M8': 'HTC One M8',
    'HTC One M9': 'HTC One M9',
    'LG G6': 'LG G6',
    'G7 ThinQ': 'LG\s?-? G7 ThinQ',
    'G8S ThinQ': 'LG G8S ThinQ',
    'G8 ThinQ': 'LG G8 ThinQ',
    'G8X ThinQ': 'LG G8X ThinQ',
    'LG K22\+': 'LG K22\+',
    'LG K40': 'LG K40',
    'LG K50': 'LG K50',
    'LG Q7 Plus': 'LG Q7\+',
    'LG Stylo ': 'LG Stylo 4',
    'LG V30': 'LG V30',
    'LG V35 ThinQ': 'LG V35 ThinQ',
    'LG V50 ThinQ': 'LG V50 ThinQ',
    'LG V60 ThinQ': 'LG V60 ThinQ',
    'Nokia 4.2': 'Nokia 4.2',
    'Nokia 7.1': 'Nokia 7.1',
    'Nokia 7.2': 'Nokia 7.2',
    'Nokia 8.3': 'Nokia 8.3',
    'Moto G 5G Plus': 'Moto G 5G Plus',
    'Moto G7 Play': 'Moto G7 Play',
    'Moto G8 Power': 'Moto G8 Power',
    'Moto G9 Plus': 'Moto G9\+',
    'Moto One Hyper': 'Moto One Hyper',
    'Motorola Edge': 'Motorola Edge',
    'Motorola Moto E6 Play': 'Motorola Moto E6 Play',
    'Motorola Moto E7 Plus': 'Motorola Moto E7 Plus',
    'Motorola Moto G4 Play': 'Motorola Moto G4 Play',
    'Motorola Moto G5 Plus': 'Motorola Moto G5\+',
    'Motorola Moto G5S': 'Motorola Moto G5S',
    'Motorola Moto G5': 'Motorola Moto G5 ',
    'Motorola Moto G6 Play': 'Motorola Moto G6 Play',
    'Motorola Moto G7': 'Motorola Moto G7 [^Play|ThinQ|Power]',
    'Motorola Moto G7 Plus': 'Motorola Moto G7\+',
    'Motorola Moto G7 Power': 'Motorola Moto G7 Power',
    'Motorola Moto G9': 'Motorola Moto G9 [^Play]',
    'Motorola Moto G9 Play': 'Motorola Moto G9 Play',
    'Motorola Moto X4': 'Motorola Moto X4',
    'Motorola Moto Z Play': 'Motorola Moto Z Play',
    'Motorola One Action': 'Motorola One Action',
    'Motorola One Fusion': 'Motorola One Fusion',
    'Motorola One Vision': 'Motorola One Vision',
    'Motorola One Zoom': 'Motorola One Zoom',
    'Motorola X4': 'Motorola X4',
    'Redmi 9': 'Xiaomi Redmi 9 ',
    'Redmi 9A': 'Xiaomi Redmi 9A',
    'Redmi 9C': 'Xiaomi Redmi 9C',
    'Redmi Note 8': 'Xiaomi Redmi Note 8 [^Pro]',
    'Redmi Note 8 Pro': 'Xiaomi Redmi Note 8 Pro',
    'Redmi Note 9': 'Xiaomi Redmi Note 9 [^Pro]',
    'Redmi Note 9 Pro': 'Xiaomi Redmi Note 9 Pro',
    'Redmi Note 9S': 'Xiaomi Redmi Note 9S',
    'Blade V20 Smart': 'ZTE Blade V20 Smart',
    'iPhone 11': 'Apple iPhone 11',
    'iPhone 7 Plus': 'Apple iPhone 7 Plus',
    'iPhone 7': 'Apple iPhone 7,? [^Plus]+',
    'iPhone 8 Plus': 'Apple iPhone 8 Plus',
    'iPhone 8': 'Apple iPhone 8,? [^Plus]',
    'iPhone SE': 'Apple iPhone SE',
    'iPhone X': 'Apple iPhone X,',
    'iPhone XR': 'Apple iPhone XR',
    'iPhone XS Max': 'Apple iPhone XS Max',
    'iPhone XS': 'Apple iPhone XS,'
}

samsung_models = ['Galaxy A51', 'Galaxy A70', 'Galaxy J3 Prime', 'Galaxy Note 10 Plus', 'Galaxy Note 10 Lite',
                  'Galaxy Note 5', 'Note 9', 'Galaxy s10 Plus', 'Galaxy S10E', 'Galaxy S20 Plus', 'Galaxy S6',
                  'Galaxy S7', 'Galaxy S8 Plus', 'Galaxy S9 Plus', 'Galaxy XCover Pro', 'Galaxy Z Flip', 'Galaxy A50',
                  'Galaxy A20S', 'Galaxy A21S', 'Galaxy A30S', 'Galaxy A31', 'Galaxy A11', 'Galaxy A10S', 'Galaxy A10E',
                  'Galaxy A01 Core', 'Galaxy Note 20', 'Galaxy S9', 'Galaxy Note 10', 'Galaxy S10', 'Galaxy S20',
                  'Galaxy A01',
                  'Galaxy S8', 'Galaxy Note 8']
oneplus_models = ['OnePlus 7 Pro', 'OnePlus 7T', 'OnePlus 6', 'OnePlus 8 Pro', 'OnePlus 8T', 'Nord N100', 'OnePlus 6T']

pixel_models = ['Pixel 4 XL', 'Pixel 3 XL', 'Pixel 3a', 'Pixel 4a', 'Pixel 5', 'Pixel 2 XL', 'Pixel 4 ', 'Pixel 3', 'Pixel 2']

huwawei_models = ['Honor 8S', 'Honor 9X', 'Huawei P30PRO', 'Huawei E837', 'Honor 10 Lite', 'Huawei Honor 9', 'Huawei Nova 5T', 'Huawei P30 Lite','Huawei Y5','Huawei Mate 10 Pro']

realme_models = ['Realme 6', 'Realme 6 Pro']

sony_models = ['Xperia 10', 'Xperia 1', 'Xperia L1', 'Xperia XZ2', 'Xperia XZ Premium']

asus_models = ['ZenFone Max']

htc_models = ['Desire 530', 'HTC One M7', 'HTC One M8', 'HTC One M9']

lg_models = ['LG G6', 'G7 ThinQ', 'G8S ThinQ', 'G8 ThinQ', 'G8X ThinQ', 'LG K22', 'LG K40', 'LG K50', 'LG Q7 Plus', 'LG Stylo', 'LG V30', 'LG V35 ThinQ', 'LG V50 ThinQ', 'LG V60 ThinQ']

nokia_models = ['Nokia 4.2', 'Nokia 7.1', 'Nokia 7.2', 'Nokia 8.3']

motorola_models = ['Moto G 5G Plus', 'Moto G7 Play', 'Moto G8 Power', 'Moto G9 Plus', 'Moto One Hyper', 'Motorola Edge', 'Motorola Moto E6 Play', 'Motorola Moto E7 Plus',
    'Motorola Moto G4 Play', 'Motorola Moto G5 Plus', 'Motorola Moto G5S', 'Motorola Moto G5', 'Motorola Moto G6 Play', 'Motorola Moto G7', 'Motorola Moto G7 Plus',
    'Motorola Moto G7 Power', 'Motorola Moto G9', 'Motorola Moto G9 Play', 'Motorola Moto X4', 'Motorola Moto Z Play',
    'Motorola One Action', 'Motorola One Fusion', 'Motorola One Vision', 'Motorola One Zoom', 'Motorola X4']

xiaomi_models = ['Redmi 9', 'Redmi 9A', 'Redmi 9C', 'Redmi Note 8', 'Redmi Note 8 Pro', 'Redmi Note 9', 'Redmi Note 9 Pro', 'Redmi Note 9S']

iphone_models = ['iPhone 11', 'iPhone 7 Plus', 'iPhone 7', 'iPhone 8 Plus', 'iPhone 8', 'iPhone SE', 'iPhone X', 'iPhone XR', 'iPhone XS Max', 'iPhone XS']

available_models = {
    "samsung": samsung_models,
    "oneplus": oneplus_models,
    "pixel": pixel_models,
    "huwawei": huwawei_models,
    "realme": realme_models,
    "sony": sony_models,
    "asus": asus_models,
    "htc": htc_models,
    "lg": lg_models,
    "nokia": nokia_models,
    "motorola": motorola_models,
    "xiaomi": xiaomi_models,
    "iphone": iphone_models
}