MODELS = {
    'Galaxy A51': 'samsung-galaxy-a51',
    'Galaxy A70': 'samsung-galaxy-a70',
    'Galaxy A71': 'samsung-galaxy-a71',
    'Galaxy J3 Prime': 'samsung-galaxy-j3-prime',
    'Galaxy Note 10 Plus': 'samsung-galaxy-note-10+',
    'Galaxy Note 10 Lite': 'samsung-galaxy-note-10-lite',
    'Galaxy Note 5': 'samsung-galaxy-note-5',
    'Note 9': 'samsung-galaxy-note-9',
    'Galaxy s10 Plus': 'samsung-galaxy-s10+',
    'Galaxy S10E': 'samsung-galaxy-s10e',
    'Galaxy S20 Plus': 'samsung-galaxy-s20+',
    'Galaxy S6': 'samsung-galaxy-s6',
    'Galaxy S7': 'samsung-galaxy-s7',
    'Galaxy S8 Plus': 'samsung-galaxy-s8+',
    'Galaxy S9 Plus': 'samsung-galaxy-s9+',
    'Galaxy XCover Pro': 'samsung-galaxy-xcover-pro',
    'Galaxy Z Flip': 'samsung-galaxy-z-flip',
    'Galaxy A50': 'samsung-galaxy-a50',
    'Galaxy A20S': 'samsung-galaxy-a20s',
    'Galaxy A21S': 'samsung-galaxy-a21s',
    'Galaxy A30S': 'samsung-galaxy-a30s',
    'Galaxy A31': 'samsung-galaxy-a31',
    'Galaxy A11': 'samsung-galaxy-a11',
    'Galaxy A10S': 'samsung-galaxy-a10s',
    'Galaxy A10E': 'samsung-galaxy-a10e',
    'Galaxy A01 Core': 'samsung-galaxy-a01-core',
    'Galaxy Note 20': 'samsung-electronics-galaxy-note-20',
    'Galaxy S9': 'samsung-galaxy-s9',
    'Galaxy Note 10': 'samsung-galaxy-note-10',
    'Galaxy S10': 'samsung-galaxy-s10',
    'Galaxy S20': 'samsung-galaxy-s20',
    'Galaxy A01': 'samsung-galaxy-a01',
    'Galaxy S8': 'samsung-galaxy-s8',
    'Galaxy Note 8': 'samsung-galaxy-note-8',
    'OnePlus 7 Pro': 'oneplus-7-pro',
    'OnePlus 7T': 'oneplus-7t',
    'OnePlus 6': 'oneplus-6',
    'OnePlus 8 Pro': 'oneplus-8-pro',
    'OnePlus 8T': 'oneplus-8t',
    'Nord N100': 'oneplus-nord-n100',
    'OnePlus 6T': 'oneplus-6t',
    'Pixel 4 XL': 'google-pixel-4-xl',
    'Pixel 3 XL': 'google-pixel-3-xl',
    'Pixel 3a': 'google-pixel-3a',
    'Pixel 4a': 'google-pixel-4a',
    'Pixel 5': 'google-pixel-5',
    'Pixel 2 XL': 'google-pixel-2-xl',
    'Pixel 4 ': 'google-pixel-4',
    'Pixel 3': 'google-pixel-3',
    'Pixel 2': 'google-pixel-2',
    'Honor 8S': 'huawei-honor-8s',
    'Honor 9X': 'huawei-honor-9x',
    'Huawei P30PRO': 'huawei-p30pro',
    'Huawei E837': 'huawei-e837',
    'Honor 10 Lite': 'huawei-honor-10-lite',
    'Huawei Honor 9': 'huawei-honor-9',
    'Huawei Nova 5T': 'huawei-nova-5t',
    'Huawei P30 Lite': 'huawei-p30-lite',
    'Huawei Y5': 'huawei-y5',
    'Huawei Mate 10 Pro': 'huawei-mate-10-pro',
    'Realme 6': 'realme-6',
    'Realme 6 Pro': 'realme-6-pro',
    'Xperia 10': 'sony-xperia-10',
    'Xperia 1': 'sony-xperia-1',
    'Xperia L1': 'sony-xperia-l1',
    'Xperia XZ2': 'sony-xperia-xz2',
    'Xperia XZ Premium': 'sony-xperia-xz-premium',
    'ZenFone Max': 'asus-zenfone-max',
    'Desire 530': 'htc-desire-530',
    'HTC One M7': 'htc-one-m7',
    'HTC One M8': 'htc-one-m8',
    'HTC One M9': 'htc-one-m9',
    'LG G6': 'lg-g6',
    'G7 ThinQ': 'lg-g7-thinq',
    'G8S ThinQ': 'lg-g8s-thinq',
    'G8 ThinQ': 'lg-g8-thinq',
    'G8X ThinQ': 'lg-g8x-thinq',
    'LG K22': 'lg-k22+',
    'LG K40': 'lg-k40',
    'LG K50': 'lg-k50',
    'LG Q7 Plus': 'lg-q7+',
    'LG Stylo ': 'lg-stylo-4',
    'LG V30': 'lg-v30',
    'LG V35 ThinQ': 'lg-v35-thinq',
    'LG V50 ThinQ': 'lg-v50-thinq',
    'LG V60 ThinQ': 'lg-v60-thinq',
    'Nokia 4.2': 'nokia-4.2',
    'Nokia 7.1': 'nokia-7.1',
    'Nokia 7.2': 'nokia-7.2',
    'Nokia 8.3': 'nokia-8.3',
    'Moto G 5G Plus': 'motorola-moto-g-5g-plus',
    'Moto G7 Play': 'motorola-moto-g7-play',
    'Moto G8 Power': 'motorola-moto-g8-power',
    'Moto G9 Plus': 'motorola-moto-g9+',
    'Moto One Hyper': 'motorola-moto-one-hyper',
    'Motorola Edge': 'motorola-edge',
    'Motorola Moto E6 Play': 'motorola-moto-e6-play',
    'Motorola Moto E7 Plus': 'motorola-moto-e7-plus',
    'Motorola Moto G4 Play': 'motorola-moto-g4-play',
    'Motorola Moto G5 Plus': 'motorola-moto-g5+',
    'Motorola Moto G5S': 'motorola-moto-g5s',
    'Motorola Moto G5': 'motorola-moto-g5 ',
    'Motorola Moto G6 Play': 'motorola-moto-g6-play',
    'Motorola Moto G7': 'motorola-moto-g7',
    'Motorola Moto G7 Plus': 'motorola-moto-g7+',
    'Motorola Moto G7 Power': 'motorola-moto-g7-power',
    'Motorola Moto G9': 'motorola-moto-g9',
    'Motorola Moto G9 Play': 'motorola-moto-g9-play',
    'Motorola Moto X4': 'motorola-moto-x4',
    'Motorola Moto Z Play': 'motorola-moto-z-play',
    'Motorola One Action': 'motorola-one-action',
    'Motorola One Fusion': 'motorola-one-fusion',
    'Motorola One Vision': 'motorola-one-vision',
    'Motorola One Zoom': 'motorola-one-zoom',
    'Motorola X4': 'motorola-x4',
    'Redmi 9': 'xiaomi-redmi-9',
    'Redmi 9A': 'xiaomi-redmi-9a',
    'Redmi 9C': 'xiaomi-redmi-9c',
    'Redmi Note 8': 'xiaomi-redmi-note-8',
    'Redmi Note 8 Pro': 'xiaomi-redmi-note-8-pro',
    'Redmi Note 9': 'xiaomi-redmi-note-9',
    'Redmi Note 9 Pro': 'xiaomi-redmi-note-9-pro',
    'Redmi Note 9S': 'xiaomi-redmi-note-9s',
    'Blade V20 Smart': 'zte-blade-v20-smart',
    'iPhone 11': 'apple-iphone-11',
    'iPhone 7 Plus': 'apple-iphone-7-plus',
    'iPhone 7': 'apple-iphone-7',
    'iPhone 8 Plus': 'apple-iphone-8-plus',
    'iPhone 8': 'apple-iphone-8',
    'iPhone SE': 'apple-iphone-se',
    'iPhone X': 'apple-iphone-x,',
    'iPhone XR': 'apple-iphone-xr',
    'iPhone XS Max': 'apple-iphone-xs-max',
    'iPhone XS': 'apple-iphone-xs,'
}

samsung_models = ['Galaxy A51', 'Galaxy A70', 'Galaxy J3 Prime', 'Galaxy Note 10 Plus', 'Galaxy Note 10 Lite',
                  'Galaxy Note 5', 'Note 9', 'Galaxy s10 Plus', 'Galaxy S10E', 'Galaxy S20 Plus', 'Galaxy S6',
                  'Galaxy S7', 'Galaxy S8 Plus', 'Galaxy S9 Plus', 'Galaxy XCover Pro', 'Galaxy Z Flip', 'Galaxy A50',
                  'Galaxy A20S', 'Galaxy A21S', 'Galaxy A30S', 'Galaxy A31', 'Galaxy A11', 'Galaxy A10S', 'Galaxy A10E',
                  'Galaxy A01 Core', 'Galaxy Note 20', 'Galaxy S9', 'Galaxy Note 10', 'Galaxy S10', 'Galaxy S20',
                  'Galaxy A01',
                  'Galaxy S8', 'Galaxy Note 8']
oneplus_models = ['OnePlus 7 Pro', 'OnePlus 7T', 'OnePlus 6', 'OnePlus 8 Pro', 'OnePlus 8T', 'Nord N100', 'OnePlus 6T']

pixel_models = ['Pixel 4 XL', 'Pixel 3 XL', 'Pixel 3a', 'Pixel 4a', 'Pixel 5', 'Pixel 2 XL', 'Pixel 4 ', 'Pixel 3', 'Pixel 2']

huwawei_models = ['Honor 8S', 'Honor 9X', 'Huawei P30PRO', 'Huawei E837', 'Honor 10 Lite', 'Huawei Honor 9', 'Huawei Nova 5T', 'Huawei P30 Lite','Huawei Y5','Huawei Mate 10 Pro']

realme_models = ['Realme 6', 'Realme 6 Pro']

sony_models = ['Xperia 10', 'Xperia 1', 'Xperia L1', 'Xperia XZ2', 'Xperia XZ Premium']

asus_models = ['ZenFone Max']

htc_models = ['Desire 530', 'HTC One M7', 'HTC One M8', 'HTC One M9']

lg_models = ['LG G6', 'G7 ThinQ', 'G8S ThinQ', 'G8 ThinQ', 'G8X ThinQ', 'LG K22', 'LG K40', 'LG K50', 'LG Q7 Plus', 'LG Stylo', 'LG V30', 'LG V35 ThinQ', 'LG V50 ThinQ', 'LG V60 ThinQ']

nokia_models = ['Nokia 4.2', 'Nokia 7.1', 'Nokia 7.2', 'Nokia 8.3']

motorola_models = ['Moto G 5G Plus', 'Moto G7 Play', 'Moto G8 Power', 'Moto G9 Plus', 'Moto One Hyper', 'Motorola Edge', 'Motorola Moto E6 Play', 'Motorola Moto E7 Plus',
    'Motorola Moto G4 Play', 'Motorola Moto G5 Plus', 'Motorola Moto G5S', 'Motorola Moto G5', 'Motorola Moto G6 Play', 'Motorola Moto G7', 'Motorola Moto G7 Plus',
    'Motorola Moto G7 Power', 'Motorola Moto G9', 'Motorola Moto G9 Play', 'Motorola Moto X4', 'Motorola Moto Z Play',
    'Motorola One Action', 'Motorola One Fusion', 'Motorola One Vision', 'Motorola One Zoom', 'Motorola X4']

xiaomi_models = ['Redmi 9', 'Redmi 9A', 'Redmi 9C', 'Redmi Note 8', 'Redmi Note 8 Pro', 'Redmi Note 9', 'Redmi Note 9 Pro', 'Redmi Note 9S']

iphone_models = ['iPhone 11', 'iPhone 7 Plus', 'iPhone 7', 'iPhone 8 Plus', 'iPhone 8', 'iPhone SE', 'iPhone X', 'iPhone XR', 'iPhone XS Max', 'iPhone XS']

available_models = {
    "samsung": samsung_models,
    "oneplus": oneplus_models,
    "pixel": pixel_models,
    "huwawei": huwawei_models,
    "realme": realme_models,
    "sony": sony_models,
    "asus": asus_models,
    "htc": htc_models,
    "lg": lg_models,
    "nokia": nokia_models,
    "motorola": motorola_models,
    "xiaomi": xiaomi_models,
    "iphone": iphone_models
}

feature_types = ["battery", "camera", "display", "face recognition", "finger print", "speaker"]