name: Deploy Frontend

on:
  push:
    branches:
      - Dev
    paths:
      - 'web-frontend/**'

  pull_request:
    branches:
      - Dev
    paths:
      - 'web-frontend/**'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{  secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    # Optional
    #- name: Build assets
    #  run: npm run assets-dev
    - name: Deploy
      run: sls deploy
    # Optional (to use with serverless-finch serverless plugin)
    #- name: Deploy assets to S3
    #  run: sls client deploy --no-delete-contents --no-confirm -s dev
