name: Deploy Frontend

on:
  push:
    branches:
      - none
    paths:
      - 'web-frontend/**'

  pull_request:
    branches:
      - none
    paths:
      - 'web-frontend/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-frontend
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install -g netlify-cli
        npm ci
        npm run build
        netlify deploy --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
