name: Deploy Frontend

on:
  push:
    branches:
      - Dev
    paths:
      - 'web-frontend/**'

  pull_request:
    branches:
      - Dev
    paths:
      - 'web-frontend/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd ./web-frontend
        npm ci
        npm run build

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=./build
      env:
        # NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: 1c8836df-d191-49e9-9032-c978384eeffc
        NETLIFY_AUTH_TOKEN: 0yGJI7-BJfRmcpaNqPcKyLcUQcp-qWZg3IHaxl43D-k
